/* delimited_doc_comment */
/*-
要約。
@var <ClassName> 変数。
@prop <ClassName> プロパティ。
@param varname1 <ClassName> 位置パラメータ。
@param &varname2 <Class:ClassName> 参照パラメータ。
@param varname3: <Object:ClassName> キーワードパラメータ。
@param &varname4: <Array[<ClassName>]> ネストしたクラス表記。
@param varname5: <DataPair Param1:<ClassName> Param2:<ClassName>> 特殊なクラス表記。
@returns <OkClass> 戻り値。
@remarks 補足説明。
*/
fn var_name = ()

/*-*/
/*- */
/*-
*/

/* delimited_comment */
/* text */
/*
text
*/
/*-/
/* */
/*
*/

/* single_line_comment */
expr -- text
