/* context_expr */
animate logical_operand, in coordsys world expr

/* context */
animate logical_operand expr
with animate logical_operand expr

at level operand expr

at time operand expr

in operand expr

coordsys world expr
coordsys operand expr
in coordsys world expr
in coordsys operand expr

about selection expr
about operand expr

with defaultAction #LogMsg

with mxsCallstackCaptureEnabled logical_operand expr
with quiet logical_operand expr
with redraw logical_operand expr

undo logical_operand expr
undo "string" logical_operand expr
undo label:operand logical_operand expr
undo varname logical_operand expr
with undo logical_operand expr

/* set_context */
set with animate logical_operand
