/*-
要約。
@var <ClassName> 変数。
@prop <ClassName> プロパティ。
@param varname1 <ClassName|UndefinedClass> 位置パラメータ。
@param &varname2 <Class:ClassName> 参照パラメータ。
@param varname3: <Object:ClassName> キーワードパラメータ。
@param &varname4: <Array[<Array[<ClassName>]>]> ネストしたクラス表記。
@param varname5: <DataPair Param1:<ClassName> Param2:<ClassName>> 特殊なクラス表記。
@param &'var name': <ClassName> 引用符で囲まれた名前。

```maxscript
"整形済みテキスト"
```
@returns <OkClass> 戻り値。
@remarks 補足説明。
*/
