/* time_literal */

/* hexadecimal_time_literal */
0xF1m
0xm

0xF1s
0xs

0xF1t
0xt

-0xF1m
-0xm

-0xF1s
-0xs

-0xF1t
-0xt

/* decimal_time_literal */
1.2m
1.m
.1m
1m

1.2s
1.s
.1s
1s

1.2f
1.f
.1f
1f

1.2t
1.t
.1t
1t

1.2m1.2s1.2f1.2t
1.m1.s1.f1.t
.1m.1s.1f.1t
1.2m1.s.1f1t
1m2s3f4t1m2s3f4t

-1.2m
-1.m
-.1m
-1m

-1.2s
-1.s
-.1s
-1s

-1.2f
-1.f
-.1f
-1f

-1.2t
-1.t
-.1t
-1t

-1.2m1.2s1.2f1.2t
-1.m1.s1.f1.t
-.1m.1s.1f.1t
-1.2m1.s.1f1t
-1m2s3f4t1m2s3f4t

/* smpte_time_literal */
1:1.2
1:1.
1:.1

-1:1.2
-1:1.
-1:.1

/* normalized_time_literal */
1.1n
1.n
.1n
1n

-1.1n
-1.n
-.1n
-1n
